export const ReasonCode = {
  ASSET_NOT_ALLOWED: "ASSET_NOT_ALLOWED",
  MARKET_NOT_ALLOWED: "MARKET_NOT_ALLOWED",
  DESTINATION_NOT_ALLOWED: "DESTINATION_NOT_ALLOWED",
  SLIPPAGE_TOO_HIGH: "SLIPPAGE_TOO_HIGH",
  MISSING_SLIPPAGE_LIMIT: "MISSING_SLIPPAGE_LIMIT",
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  EXECUTION_FREQUENCY_LIMIT: "EXECUTION_FREQUENCY_LIMIT",
  SESSION_SCOPE_DENIED: "SESSION_SCOPE_DENIED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  KILL_SWITCH_ACTIVE: "KILL_SWITCH_ACTIVE",
  STALE_QUOTE: "STALE_QUOTE",
  REPEATED_FAILURE_LIMIT: "REPEATED_FAILURE_LIMIT",
  CREDIT_SOURCE_NOT_FOUND: "CREDIT_SOURCE_NOT_FOUND",
  INSUFFICIENT_LIQUIDITY: "INSUFFICIENT_LIQUIDITY",
  INVALID_INTENT: "INVALID_INTENT"
} as const;

export type ReasonCode = (typeof ReasonCode)[keyof typeof ReasonCode];
